// Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_ERROR = "LOGIN_ERROR";

// Logout
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// Incidents
export const INCIDENTS_SUCCESS = "INCIDENTS_SUCCESS";
export const INCIDENTS_LOADING = "INCIDENTS_SUCCESS";
export const INCIDENTS_ERROR = "INCIDENTS_ERROR";
export const INCIDENT_ATTEND_LIST = "INCIDENT_ATTEND_LIST";
export const INCIDENT_ATTEND_LIST_ERROR = "INCIDENT_ATTEND_LIST_ERROR";

// BottomSheet
export const BOTTOMATTENDEDSHEETOPEN = "BOTTOMATTENDEDSHEETOPEN";
export const BOTTOMATTENDEDSHEETCLOSE = "BOTTOMATTENDEDSHEETCLOSE";
export const BOTTOMDISMISSSHEETOPEN = "BOTTOMDISMISSSHEETOPEN";
export const BOTTOMDISMISSSHEETCLOSED = "BOTTOMDISMISSSHEETCLOSED";

// incidents
export const INCIDENT_ACTION_SUCCESS = "INCIDENT_ACTION_SUCCESS";
export const INCIDENT_ACTION_LOADING = "INCIDENT_ACTION_LOADING";
export const INCIDENT_ACTION_ERROR = "INCIDENT_ACTION_ERROR";
