export const Route = {
    APPSTACK: "AFTERLOGIN",
    AUTHSTACK: "BEFORELOGIN",
    IPLOGIN: "IPLOGIN",
    UNATTENDED: "UNATTENDED",
    INCIDENTS: "INCIDENTS",
    LIVESTATUS: "LIVESTATUS",
    VIEWFULLIMAGE: "VIEWFULLIMAGE"
}